
```{r, echo = FALSE, results='asis', eval = FALSE}
cow::borrow_chapter(
  doc_path = "Getting-started.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```

```{r, echo = FALSE, results='asis', eval = FALSE}
cow::borrow_chapter(
  doc_path = "Getting-started.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```

```{r, echo = FALSE, results='asis', eval = FALSE}
cow::borrow_chapter(
  doc_path = "Content-creation-tips.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```


```{r, echo = FALSE, results='asis', eval = FALSE}
cow::borrow_chapter(
  doc_path = "Start-a-new-course.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```

```{r, echo = FALSE, results='asis', eval = FALSE}
cow::borrow_chapter(
  doc_path = "Setting-up-your-repository-files.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```

```{r, echo = FALSE, results='asis', eval = FALSE}
cow::borrow_chapter(
  doc_path = "Setting-up-your-repository-settings.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```

```{r, echo = FALSE, results='asis', eval = FALSE}
cow::borrow_chapter(
  doc_path = "Setting-up-GitHub-secrets.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```

```{r, echo = FALSE, results='asis', eval = FALSE}
cow::borrow_chapter(
  doc_path = "Adding-content-to-a-course.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```

```{r, echo = FALSE, results='asis', eval = FALSE}
cow::borrow_chapter(
  doc_path = "About-pull-request-review.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```

```{r, echo = FALSE, results='asis', eval = FALSE}
cow::borrow_chapter(
  doc_path = "Setting-up-images-and-graphics.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```
