
# OTTR Tools

```{r, include = FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "Citations.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "Using-Docker.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "Publishing-on-Coursera.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "Spell-check.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "Leanpub-conversion-tips.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "Borrowing-chapters-between-courses.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "Generate-docx-output.md",
  repo_name = "wiki/jhudsl/OTTR_Template"
)
```
