
# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/How-to-give-credits).

&nbsp;
&nbsp;

|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor(s)|[Candace Savonen], [Carrie Wright]|
|Content Author(s)| [Ava Hoffman]|
|Content Editor(s)/Reviewer(s) | [Frederick Tan], [Katherine Cox], [Ava Hoffman], [Candace Savonen], [Carrie Wright], [Ira Gooding]|
|Content Director(s) |[Frederick Tan], [Jeff Leek], [Candace Savonen], [Carrie Wright]|
|Content Consultants|[Ira Gooding]|
|**Technical**||
|Course Publishing Engineer|[Candace Savonen]|
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Candace Savonen]|
|Package Developers ([Leanbuild])[John Muschelli], [Candace Savonen], [Carrie Wright]|
|**Art and Design**||
|Illustrator(s)| [Candace Savonen],  [Carrie Wright]|
|Figure Artist(s)| [Candace Savonen],  [Carrie Wright]|
|**Funding**||
|Funder|[National Cancer Institute (NCI)](https://www.cancer.gov/) UE5 CA254170|
|Funding Staff| Emily Voeglein, Fallon Bachman|

&nbsp;

```{r, echo = FALSE}
devtools::session_info()
```

<!-- Author information -->
[Candace Savonen]: https://www.cansavvy.com/
[Carrie Wright]: https://carriewright11.github.io/
[Ira Gooding]: https://publichealth.jhu.edu/faculty/4130/ira-gooding
[Jeff Leek]: https://jtleek.com/
[John Muschelli]: https://johnmuschelli.com/
[Sarah Wheelan]: https://www.hopkinsmedicine.org/profiles/details/sarah-wheelan

<!-- Links -->

[Leanbuild]: https://github.com/jhudsl/leanbuild

<!-- Fill out this table using these instructions: https://github.com/jhudsl/DaSL_Course_Template_Bookdown/wiki/How-to-give-credits

For JHU courses, You will need to add Ira as a credit:

|Content Publisher|[Ira Gooding]|
...
[Ira Gooding]: https://publichealth.jhu.edu/faculty/4130/ira-gooding
-->
